//
// Created by orion on 10.03.17.
//

#ifndef LIFE_ERRORSCOMUNICATS_H
#define LIFE_ERRORSCOMUNICATS_H

#define MEMORY_EXHAUSTION -9111
#define FILE_CAN_NOT_OPEN_TO_WRITE -9112
#define FILE_SIZE_VALUE -9113 //Error: can not read size value
#define FILE_CELLS_VALUES -9114 //Error: can not read cells value
#define FILE_CAN_NOT_OPEN_TO_READ -9115
#define PNG_CAN_NOT_OPEN -9116    //Error: can not open file for writting
#define PNG_CREATE_WRITE_STRUCT_FAILED -9117
#define PNG_CREATE_INFO_STRUCT_FAILED -9118
#define PNG_INIT_TO_ERROR -9119
#define PNG_WRITTING_HEADRE_WRITE -9120
#define PNG_WRITING_BYTES -9121
#define PNG_END_OF_WRITE_ERROR -9122
#define CONFIGURATION_FILE_CAN_NOT_OPEN -9123
#define INVALID_VALUE_NEIGHBORHOOD_SETTINGS -9124
#define INVALID_VALUE_DEFAULT_BOARD_SIZE -9125
#define INVALID_VALUE_EDGE_SETTINGS -9126
#define INVALID_VALUE_DEFAULT_GENERATION_COUNT -9127
#define INVALID_VALUE_CELL_SIZE -9128
#define FILE_INVALID_COUNT_OF_ARGUMENTS -9129

#endif //LIFE_ERRORSCOMUNICATS_H
